# Generated by Django 6.0.5 on 2026-06-05 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_socialaccount'),
        ('workspaces', '0003_workspacemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='connected_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='workspaces.workspace'),
        ),
    ]
