# Generated by Django 6.0.5 on 2026-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0003_socialaccount_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
