# Generated by Django 6.0.5 on 2026-06-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_activitylog'),
        ('workspaces', '0003_workspacemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trigger', models.CharField(choices=[('post_published', 'Post Published'), ('analytics_created', 'Analytics Created'), ('social_account_connected', 'Social Account Connected')], max_length=50)),
                ('action', models.CharField(choices=[('send_notification', 'Send Notification'), ('generate_report', 'Generate Report')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_rules', to='workspaces.workspace')),
            ],
        ),
    ]
