# Generated by Django 6.0.5 on 2026-06-07 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('workspaces', '0003_workspacemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentanalytics',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='workspaces.workspace'),
            preserve_default=False,
        ),
    ]
